CREATE TABLE IF NOT EXISTS mainmenu(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
url TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS products(
id INTEGER PRIMARY KEY AUTOINCREMENT,
product TEXT NOT NULL,
price INTEGER NOT NULL,
image BLOB DEFAULT NULL,
time INTEGER NOT NULL
);

